DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
user_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
nickname VARCHAR(20) UNIQUE NOT NULL,
email VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
profile_img VARCHAR(255),
tier_level INT NOT NULL DEFAULT 1,
user_post_count INT NOT NULL DEFAULT 0,
deleted_at TIMESTAMP NULL, 
status BOOLEAN NOT NULL DEFAULT true
);